name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build & Push Docker Image
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: action/checkout@v3
    - name: Build & Publish Docker Image to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: mediabacklog2023/getting-started
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
